# yaml-language-server: $schema=./schema.default.json
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: "flexible_data_centers"
  disable_progressbar: true
  shared_resources:
    policy: false
  shared_cutouts: true

data_center:
  dsr:
    enable: true
    capital_cost: 0.1
    marginal_cost: 0.1 # Assuming shifting load is for free to the ESM, as the DC will require to deliver this DSR in order to gain access to the system
    p_pct_nom: 0.05
    shift_hours: 12
  load:
    profile: High Voltage Import
    profile_year: 2024
  "on-site generation":
    enable: false
    p_pct_nom: 0.2
    reference_technology: OCGT
  "on-site storage":
    enable: false
    p_pct_nom: 0.2
    shift_hours: 6
    reference_technology: battery
  grid_connection: "Grid to data center"

clustering:
  temporal:
    resolution_sector: 1000SEG
