# yaml-language-server: $schema=./schema.default.json
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

tutorial: true

run:
  name: "baseline_no_flex_28c_3h"
  disable_progressbar: true
  shared_resources:
    policy: false
  shared_cutouts: true

countries: ['AT', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI', 'SK']

snapshots:
  start: "2019-01-01"
  end: "2019-12-31"

data_center:
  dsr:
    enable: false
    capital_cost: 0.1
    marginal_cost: 0.1
    p_pct_nom: 0.05
    shift_hours: 12
  load:
    profile: High Voltage Import
    profile_year: 2024
    method: max
  "on-site generation":
    enable: true
    p_pct_nom: 0.3
    reference_technology: OCGT
  "on-site storage":
    enable: true
    p_pct_nom: 0.3
    shift_hours: 6
    reference_technology: battery
  grid_connection: "Grid to data center"
