# yaml-language-server: $schema=./schema.default.json
# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: "inflexible_data_centers"
  disable_progressbar: true
  shared_resources:
    policy: false
  shared_cutouts: true

data_center:
  dsr:
    enable: false
    capital_cost: 0.1
    marginal_cost: 0.1
    p_pct_nom: 0.05
    shift_hours: 6
  load:
    profile: High Voltage Import
    profile_year: 2024
    method: mean
  "on-site generation":
    enable: false
    p_pct_nom: 0.2
    reference_technology: OCGT
  "on-site storage":
    enable: false
    p_pct_nom: 0.2
    shift_hours: 6
    reference_technology: battery
  grid_connection: "Grid to data center"
